// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbpovprvgoqzjjsaeegt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJicG92cHJ2Z29xempqc2FlZWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjM1MDYsImV4cCI6MjA3MDI5OTUwNn0.S0SnwTUjmSum8rhZRK1F2MU0jzCLfFEuVxahC_sqfu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});